ALTER TABLE ALIAS ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE GUILD ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE IGNORE ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE READABLE_BOT ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE READABLE_CHANNEL ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE VCS_USER ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE VC_TITLE ADD VERSION INT DEFAULT 0 NOT NULL;
ALTER TABLE VOICE ADD VERSION INT DEFAULT 0 NOT NULL;